### ISSUE TITLE
Error when trying to run levee serial

### ISSUE THREAD

**Issue by felicio93** [schism-dev/RiverMeshTools#11]
@feiye-vims, I noticed I get an error when trying to run make_river_map using default configuration for levees.

**Here is the script (adapted from sample_barrier.py):**

def serial():
    from RiverMapper.make_river_map import make_river_map
    from RiverMapper.config_river_map import ConfigRiverMap
    from glob import glob

    river_map_config = ConfigRiverMap.Levees()
    cudem_tif_fnames = glob('./Inputs/DEMs/CuDEM/*.tif')
    crm_tif_fnames = glob('./Inputs/DEMs/CRM/*.tif')

    make_river_map(
        tif_fnames = cudem_tif_fnames + crm_tif_fnames,
        thalweg_shp_fname='./Inputs/Shapefiles/levee_v3_centerline_redist_5m.shp',
        output_dir = './Outputs/',
        **river_map_config.optional,
    )
    
  
  **The error message:**
  line 1619, in make_river_map
    elevs = get_elev_from_tiles(line[:, 0],line[:, 1], S_list, scale=elev_scale)
UnboundLocalError: local variable 'S_list' referenced before assignment

**Comment by feiye-vims** [comment]
Thanks. I probably introduced some bugs recently; I'll take a look soon.

**Comment by feiye-vims** [comment]
I've fixed the problem. Let me know if you find anything else out of place.

**Comment by felicio93** [comment]
Everything looks good. Thanks Fei!
