### ISSUE TITLE
DEM JSON usage

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/RiverMeshTools#2]
As you know for MPI parallel RiverMapper, currently it's necessary to use DEM JSON input file to specify the DEMs. I'm trying to write a script that handles all the steps from RiverMapper and pyDEM in both serial and mpi-parallel mode. When specifying DEMs I usually pass in a list of items, however if I do so, I cannot use parallel RiverMapper, because it only accepts a `glob_pattern`, which overwrites the `file_list`:
https://github.com/schism-dev/RiverMeshTools/blob/46225aa48fcbe50392ba721f93edf63273c4d994/RiverMapper/RiverMapper/river_map_tif_preproc.py#L209

What I'd like to do is to specify the `file_list` itself. Would it be possible to change the code such that `file_list` is just *updated* based on the patterns in the `glob_pattern` instead? Something like:
```python
dem_dict[k]['file_list'].extend(glob(dem_dict[k]['glob_pattern']))
```

**Comment by feiye-vims** [comment]
I changed it to:

```python
        # if glob pattern returns any files, put them into the file_list
        dem_dict[k]['file_list'].append(glob(dem_dict[k]['glob_pattern']))
        # get unique file names
        dem_dict[k]['file_list'] = list(set(dem_dict[k]['file_list']))
```
, so that you can directly specify a file list in the json file and set glob_pattern as an empty string.

**Comment by SorooshMani-NOAA** [comment]
Thanks, I tested and it works with `file_list` as well now. I didn't test combination of `file_list` and `glob_pattern`, but that should work as well based on the code.
