### ISSUE TITLE
Cache directory path

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/RiverMeshTools#3]
Currently the directory used for caching DEM data is always created under current directory:
https://github.com/schism-dev/RiverMeshTools/blob/46225aa48fcbe50392ba721f93edf63273c4d994/RiverMapper/RiverMapper/river_map_mpi_driver.py#L110-L132

Would it be possible for the cache dir to be specified as a part of either config object (`Config_make_river_map`) or just argument to `river_map_mpi_driver` instead?

**Comment by feiye-vims** [comment]
Okay, I'll make the change soon.

**Comment by feiye-vims** [comment]
I set it as an argument of river_map_mpi_driver.

The next commit will reflect this change.

**Comment by SorooshMani-NOAA** [comment]
Thanks it works. The only thing that can be improved is to accept `pathlib.Path` objects as input as well. Right now I can only pass `str` object with an ending `'/'` for it work fine. I'll close the ticket, because the main issue is addressed.

**Comment by feiye-vims** [comment]
@SorooshMani-NOAA I've adapted it to pathlib.Path
